# Generated by Django 2.2.13 on 2020-07-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20200711_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test_passed',
            new_name='tests_passed',
        ),
    ]
