# Generated by Django 2.2.13 on 2020-06-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_tests', '0003_auto_20200625_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestResultDetail',
            new_name='TestRunDetail',
        ),
    ]
