# Generated by Django 2.2.13 on 2020-06-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20200626_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestRunDetail',
            new_name='TestResultDetail',
        ),
    ]
