# Generated by Django 2.2.13 on 2020-07-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_tests', '0006_auto_20200630_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
