# Generated by Django 2.2.13 on 2020-07-24 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_testresult_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultdetail',
            name='is_correct',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
