"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from app.settings.components.base import INSTALLED_APPS, BASE_DIR, MIDDLEWARE



DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS += [

    'django_extensions',
    'debug_toolbar',

    ]

MIDDLEWARE += [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'core.middlewares.simple_middleware',
]

ROOT_URLCONF = 'app.urls'


WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

